# Generated by Django 4.0.3 on 2022-03-18 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_expired',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_ended',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_started',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=150, null='True'),
        ),
        migrations.AlterField(
            model_name='project',
            name='service_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.servicescategory'),
        ),
    ]
