# Generated by Django 4.0.3 on 2022-03-18 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_project_date_expired_alter_project_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='paid_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Not Paid', 'Not Paid')], default='Not Paid', max_length=150),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('amount_paid', models.FloatField()),
                ('date_paid', models.DateField()),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.project')),
            ],
        ),
    ]
